### ISSUE TITLE
:heavy_check_mark: setup Kanban board 

### ISSUE THREAD

**Issue by mahabubx7** [mahabubx7/food-hobbies#41]
[GitHub project link](https://github.com/mahabubx7/js-capstone/projects/1)
**https://github.com/mahabubx7/js-capstone/projects/1**

:busts_in_silhouette:  Team (2 members only)
- :man_technologist: @mahabubx7 
- :man_technologist: @fickryiman

**Comment by TedLivist** [comment]
## STATUS: CHANGES REQUIRED ♻️ ♻️

Hi @mahabubx7 and @fickryiman,

Good job so far!
✔️ Kanban columns are complete
However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
- [x] You should have 15 tasks since this is a two-man project. Kindly remove all Student C (reservation) tasks.

- [x] Kindly choose who would be Students A and B and assign your tasks properly. Ensure the group tasks are also assigned (they can have multiple assignees)

  ![andre-assigned](https://user-images.githubusercontent.com/36542986/232441128-b8bcdbf8-15ca-4d5e-912b-00e991251fb8.jpg)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Issue for re-reviews. You should use the same Issue submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by wayungi** [comment]
Hi @fickryiman  & @mahabubx7 , 

![image](https://user-images.githubusercontent.com/99656687/220082459-c1b049c7-5498-42e7-942b-ec7a05d3e603.png)

Great work, your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

**Remember: Every finish line 🏁  is the beginning of a new race 🐎** 

## Highlights
- [x] All student C tasks have been removed ✔️ 
- [x] All tasks have assignees ✔️  

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
